[package]
name = "rust4d_render"
version = "0.1.0"
edition = "2021"

[dependencies]
rust4d_math.workspace = true
rust4d_input.workspace = true
wgpu.workspace = true
winit.workspace = true
bytemuck.workspace = true
log.workspace = true
